import {
  Stethoscope,
  ShieldAlert,
  Car,
  Leaf,
  Briefcase,
  GraduationCap,
  Users,
  Home,
  Plane,
  Cpu,
  Apple,
  Gamepad2,
  Palette,
  ShoppingCart,
  Dumbbell,
  Languages,
  Scale,
  Hospital,
  Bone,
  Siren,
  UserRound,
  Building2,
  Sparkles,
  ThumbsUp,
  ThumbsDown,
  AlertTriangle,
  Lightbulb,
  TrendingUp,
  MessageCircle,
  BookOpen,
  Target,
  ShieldCheck,
  Clock,
  Compass,
  HeartHandshake,
  PawPrint,
  Shirt,
  Users2,
  ArrowRightLeft,
  Link2,
  SpellCheck,
  MessagesSquare,
  Sparkle,
  Waypoints,
  type LucideIcon,
} from "lucide-react";

export const topicIcons: Record<string, LucideIcon> = {
  gesundheit: Stethoscope,
  kriminalitaet: ShieldAlert,
  verkehr: Car,
  umwelt: Leaf,
  arbeit: Briefcase,
  bildung: GraduationCap,
  familie: Users,
  wohnen: Home,
  reisen: Plane,
  technologie: Cpu,
  ernaehrung: Apple,
  freizeit: Gamepad2,
  kultur: Palette,
  konsum: ShoppingCart,
  sport: Dumbbell,
  sprache: Languages,
  politik: Scale,
  krankenpflege: Hospital,
  koerper: Bone,
  notfall: Siren,
  person: UserRound,
  stadtland: Building2,
  ehrenamt: HeartHandshake,
  haustiere: PawPrint,
  aussehen: Shirt,
  beziehungen: Users2,
  "verben-praep-akkusativ": ArrowRightLeft,
  "verben-praep-dativ": ArrowRightLeft,
  "adjektive-praepositionen": Sparkle,
  konnektoren: Link2,
  "grammatik-strukturen": SpellCheck,
  redemittel: MessagesSquare,
};

/** Every per-preposition mindmap shares the same radial-mindmap icon. */
const praepositionIcon: LucideIcon = Waypoints;

export function getTopicIcon(slug: string): LucideIcon {
  if (slug.startsWith("praep-")) return praepositionIcon;
  return topicIcons[slug] ?? Leaf;
}

export const branchIconPool: LucideIcon[] = [
  Sparkles,
  ThumbsUp,
  AlertTriangle,
  Lightbulb,
  TrendingUp,
  MessageCircle,
  BookOpen,
  Target,
  ShieldCheck,
  Clock,
  Compass,
  ThumbsDown,
];

export function getBranchIcon(index: number): LucideIcon {
  return branchIconPool[index % branchIconPool.length];
}
